### PR TITLE
Improve Milestones layout

### LINKED ISSUE #21: Improve milestones visualization
At the bottom of the time tracker component, there is a list of participants with the last milestone displayed.
image

- [x] Image should be clickable

The public display of milestones looks like this:
image

- [x] It should show the milestones per activity
- [x] It should be a way to show the images bigger. A possibility is to use a slideshow for every activity
```
Some activity
-slide show of milestones for this activity for the user-
Another activity
-slide show of milestones for this activity for the user-
```
- [x] Add milestones_controller tests

### PR DESCRIPTION
**Pull request by verarojman**
Closes #21

- [x] Improve assignees list in index view
- [x] Improve milestones view
- [x] Show milestones per-activity
- [x] DRY-up code (helpers)
- [x] Add specs

### Time Tracker index view

image

### User milestones view

image

### CODE REVIEW

**Review by microstudi — COMMENTED** [review]
is the milestone_placeholder.jpeg used?

**Comment by verarojman** [comment]
> is the milestone_placeholder.jpeg used?

Nope, I deleted it

**Comment by microstudi** [comment]
Love this new layout @verarojman!
we will need to test some usability issues that could arise, for instance how to quickly show to the user the most relevant time counter to work on. If it is very low in the page it might be a nuisance

**Comment by verarojman** [comment]
@microstudi I totally agree with you :) I'll create an issue

**Pull request merged**
